theme: jekyll-theme-cayman
title: How-to describe Legislation using schema.org markup
description: A guide on how best to disseminate legislation metadata for wide consumption by search engines and more 
